<?php
session_start();require_once 'database.php';require_once 'mailer.php';
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($_SESSION['csrf_token'],$_POST['csrf_token']??'')){http_response_code(403);exit('Invalid security token.');}
 $email=strtolower(trim($_POST['email']??''));$q=$pdo->prepare('SELECT id,name,email FROM users WHERE email=? AND status="active" LIMIT 1');$q->execute([$email]);$u=$q->fetch();
 if($u){$token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);$pdo->prepare('UPDATE password_resets SET used_at=CURRENT_TIMESTAMP WHERE user_id=? AND used_at IS NULL')->execute([$u['id']]);$pdo->prepare('INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES(?,?,?)')->execute([$u['id'],$hash,date('Y-m-d H:i:s',time()+3600)]);$link='http://'.($_SERVER['HTTP_HOST']??'localhost').rtrim(dirname($_SERVER['PHP_SELF']),'/').'/reset-password.php?token='.urlencode($token);smtp_send($u['email'],'Husika Events password reset',"Hello {$u['name']},\n\nUse this link within 1 hour to reset your password:\n{$link}\n\nIf you did not request this, ignore this email.");}
 $msg='If the account exists, password reset instructions have been sent.';
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forgot Password | Husika</title><style>body{font-family:Arial;background:#f5f5f2;display:grid;place-items:center;min-height:100vh}.card{background:#fff;padding:35px;border-radius:12px;width:min(420px,92%);box-shadow:0 10px 35px #0001}input{width:100%;padding:13px;margin:10px 0 18px}button{width:100%;padding:13px;background:#111;color:#fff;border:0;border-radius:6px}.msg{background:#e8f5ec;padding:12px}</style></head><body><div class="card"><h2>Reset your password</h2><?php if($msg):?><p class="msg"><?=htmlspecialchars($msg)?></p><?php endif;?><form method="POST"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token'])?>"><label>Email address</label><input type="email" name="email" required><button>Send Reset Instructions</button></form><p><a href="login.php">Back to login</a></p></div></body></html>
