<?php
session_start();require_once 'database.php';
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));$forced=!empty($_GET['forced']);$token=$_GET['token']??'';$error='';$ok='';
if($forced&&empty($_SESSION['reset_user_id'])){$forced=false;}
if(!$forced&&$token){$q=$pdo->prepare('SELECT * FROM password_resets WHERE token_hash=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP ORDER BY id DESC LIMIT 1');$q->execute([hash('sha256',$token)]);$reset=$q->fetch();}else$reset=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($_SESSION['csrf_token'],$_POST['csrf_token']??'')){http_response_code(403);exit('Invalid security token.');}
 $pw=$_POST['password']??'';$confirm=$_POST['confirm_password']??'';$uid=$forced?(int)$_SESSION['reset_user_id']:(int)($reset['user_id']??0);
 $strong=strlen($pw)>=10&&preg_match('/[A-Z]/',$pw)&&preg_match('/[a-z]/',$pw)&&preg_match('/\d/',$pw)&&preg_match('/[^A-Za-z0-9]/',$pw);
 if(!$uid||!$strong||$pw!==$confirm)$error='Use a strong password of at least 10 characters with upper/lowercase letters, a number and a symbol, and make both passwords match.';else{$pdo->prepare('UPDATE users SET password_hash=?,must_reset_password=0 WHERE id=?')->execute([password_hash($pw,PASSWORD_DEFAULT),$uid]);$pdo->prepare('UPDATE password_resets SET used_at=CURRENT_TIMESTAMP WHERE user_id=? AND used_at IS NULL')->execute([$uid]);$ok='Password changed successfully. You can now log in.';unset($_SESSION['reset_user_id']);}
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reset Password | Husika</title><style>body{font-family:Arial;background:#f5f5f2;display:grid;place-items:center;min-height:100vh}.card{background:#fff;padding:35px;border-radius:12px;width:min(420px,92%);box-shadow:0 10px 35px #0001}input{width:100%;padding:13px;margin:10px 0 18px}button{width:100%;padding:13px;background:#111;color:#fff;border:0;border-radius:6px}.error{color:#a00}.ok{background:#e8f5ec;padding:12px}</style></head><body><div class="card"><h2>Create a new password</h2><?php if($error):?><p class="error"><?=htmlspecialchars($error)?></p><?php endif;?><?php if($ok):?><p class="ok"><?=htmlspecialchars($ok)?></p><a href="login.php">Go to login</a><?php else: ?><form method="POST"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token'])?>"><label>New password</label><input type="password" name="password" minlength="10" required><label>Confirm password</label><input type="password" name="confirm_password" minlength="10" required><button>Change Password</button></form><?php endif;?></div></body></html>
